#!/usr/bin/env bash
set -euo pipefail
SKILLS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ERRORS=0

run_test() {
  local platform="$1" flag_dir="$2" dest_rel="$3"
  local TMP; TMP=$(mktemp -d)
  mkdir -p "$TMP/$flag_dir"
  "$SKILLS_DIR/install.sh" --target "$platform" --project-dir "$TMP"
  local dest="$TMP/$dest_rel"
  if [[ ! -f "$dest" ]]; then
    echo "FAIL [$platform]: $dest not created"; ERRORS=$((ERRORS+1)); rm -rf "$TMP"; return
  fi
  grep -qF "<!-- Generated by chakraview" "$dest"  || { echo "FAIL [$platform]: missing start sentinel"; ERRORS=$((ERRORS+1)); }
  grep -qF "<!-- /Generated by chakraview -->" "$dest" || { echo "FAIL [$platform]: missing end sentinel"; ERRORS=$((ERRORS+1)); }
  grep -q "## chakraview:workflow" "$dest"         || { echo "FAIL [$platform]: missing workflow section"; ERRORS=$((ERRORS+1)); }

  # Sentinel update preserves user content
  echo -e "\n## My custom section\nkeep me" >> "$dest"
  "$SKILLS_DIR/install.sh" --target "$platform" --project-dir "$TMP"
  grep -q "## My custom section" "$dest" && echo "OK [$platform]: user content preserved" || { echo "FAIL [$platform]: user content removed on update"; ERRORS=$((ERRORS+1)); }

  rm -rf "$TMP"
}

run_test copilot ".github"  ".github/copilot-instructions.md"
run_test codex   "."        "AGENTS.md"
run_test gemini  "."        "GEMINI.md"

[[ $ERRORS -gt 0 ]] && echo "$ERRORS error(s)" && exit 1
echo "Aggregate platforms: all tests passed"
